("君のこころは輝いてるかい？", "君のこころは輝いてるかい？", "Aqours", "畑 亜貴", "光増ハジメ", "EFFY", "2015-10-07", 2, 1),
("Step! ZERO to ONE", "君のこころは輝いてるかい？", "Aqours", "畑 亜貴", "高田 暁", "高田 暁", "2015-10-07", 2, 2),
("Aqours☆HEROES", "君のこころは輝いてるかい？", "Aqours", "畑 亜貴", "渡辺和紀", "渡辺和紀", "2015-10-07", 2, 3),
("恋になりたいAQUARIUM", "恋になりたいAQUARIUM", "Aqours", "畑 亜貴", "佐々倉有吾", "渡辺和紀", "2016-04-27", 2, 1),
("待ってて愛のうた", "恋になりたいAQUARIUM", "Aqours", "畑 亜貴", "山口朗彦", "山口朗彦", "2016-04-27", 2, 2),
("届かない星だとしても", "恋になりたいAQUARIUM", "Aqours", "畑 亜貴", "宮崎 誠", "宮崎 誠", "2016-04-27", 2, 3),
("元気全開DAY！DAY！DAY！", "元気全開DAY！DAY！DAY！", "CYaRon！", "畑 亜貴", "高田 暁", "高田 暁", "2016-05-11", 2, 1),
("夜空はなんでも知ってるの？", "元気全開DAY！DAY！DAY！", "CYaRon！", "畑 亜貴", "Kon-K", "Kon-K", "2016-05-11", 2, 2),
("トリコリコPLEASE!!", "トリコリコPLEASE!!", "AZALEA", "畑 亜貴", "宮崎 誠", "宮崎 誠", "2016-05-25", 2, 1),
("ときめき分類学", "トリコリコPLEASE!!", "AZALEA", "畑 亜貴", "金崎真士", "金崎真士", "2016-05-25", 2, 2),
("Strawberry Trapper", "Strawberry Trapper", "Guilty Kiss", "畑 亜貴", "金崎真士", "金崎真士", "2016-06-08", 2, 1),
("Guilty Night, Guilty Kiss!", "Strawberry Trapper", "Guilty Kiss", "畑 亜貴", "R・O・N", "R・O・N", "2016-06-08", 2, 2),
("青空Jumping Heart", "青空Jumping Heart", "Aqours", "畑 亜貴", "伊藤 賢, 光増ハジメ", "EFFY", "2016-07-20", 2, 1),
("ハミングフレンド", "青空Jumping Heart", "Aqours", "畑 亜貴", "桑原 聖(Arte Refact)", "酒井拓也(Arte Refact)", "2016-07-20", 2, 2),
("ユメ語るよりユメ歌おう", "ユメ語るよりユメ歌おう", "Aqours", "畑 亜貴", "山口朗彦", "山口朗彦", "2016-08-24", 2, 1),
("サンシャインぴっかぴか音頭", "ユメ語るよりユメ歌おう", "Aqours", "畑 亜貴", "伊藤真澄", "EFFY", "2016-08-24", 2, 2),
("決めたよHand in Hand", "決めたよHand in Hand／ダイスキだったらダイジョウブ！", "Aqours", "畑 亜貴", "渡辺拓也", "渡辺拓也", "2016-08-03", 2, 1),
("ダイスキだったらダイジョウブ！", "決めたよHand in Hand／ダイスキだったらダイジョウブ！", "Aqours", "畑 亜貴", "高田 暁", "高田 暁", "2016-08-03", 2, 2),
("夢で夜空を照らしたい", "夢で夜空を照らしたい／未熟DREAMER", "Aqours", "畑 亜貴", "光増ハジメ", "EFFY", "2016-09-14", 2, 1),
("未熟DREAMER", "夢で夜空を照らしたい／未熟DREAMER", "Aqours", "畑 亜貴", "渡辺和紀", "渡辺和紀", "2016-09-14", 2, 2),
("Pops heartで踊るんだもん！", "TVアニメ1期Blu-ray第1巻特装限定版", "Aqours", "畑 亜貴", "高田 暁", "高田 暁", "2016-09-27", 2, 1),
("空も心も晴れるから", "TVアニメ1期Blu-ray第2巻特装限定版", "高海千歌, 桜内梨子, 渡辺曜", "畑 亜貴", "原田 篤(Arte Refact)", "脇 眞富(Arte Refact)", "2016-10-26", 2, 1),
("想いよひとつになれ", "想いよひとつになれ／MIRAI TICKET", "Aqours", "畑 亜貴", "佐伯高志", "佐伯高志", "2016-11-09", 2, 1),
("MIRAI TICKET", "想いよひとつになれ／MIRAI TICKET", "Aqours", "畑 亜貴", "EFFY", "EFFY", "2016-11-09", 2, 2),
("ジングルベルがとまらない", "ジングルベルがとまらない", "Aqours", "畑 亜貴", "光増ハジメ", "EFFY", "2016-11-23", 2, 1),
("聖なる日の祈り", "ジングルベルがとまらない", "Aqours", "畑 亜貴", "田中俊亮", "田中俊亮, 伊藤 賢", "2016-11-23", 2, 2),
("Waku-Waku-Week!", "TVアニメ1期Blu-ray第3巻特装限定版", "津島善子, 国木田花丸, 黒澤ルビィ", "畑 亜貴", "ラムシーニ, 内田陽吾", "小高光太郎, ラムシーニ", "2016-11-25", 2, 1),
("SELF CONTROL!!", "Sailing to the Sunshine", "Saint Snow", "畑 亜貴", "河田貴央", "河田貴央", "2016-11-30", 2, 15),
("Daydream Warrior", "TVアニメ1期Blu-ray第4巻特装限定版", "Aqours", "畑 亜貴", "前口 渉", "中土智博", "2016-12-22", 2, 1),
("G線上のシンデレラ", "TVアニメ1期Blu-ray第5巻特装限定版", "松浦果南, 黒澤ダイヤ, 小原鞠莉", "畑 亜貴", "石倉誉之", "ラムシーニ, 石倉誉之", "2017-01-27", 2, 1),
("スリリング・ワンウェイ", "TVアニメ1期Blu-ray第6巻特装限定版", "Aqours", "畑 亜貴", "藤井亮太, 小高光太郎", "藤井亮太, 小高光太郎", "2017-02-24", 2, 1),
("太陽を追いかけろ！", "TVアニメ1期Blu-ray第7巻特装限定版", "Aqours", "畑 亜貴", "松田彬人", "松田彬人", "2017-03-24", 2, 1),
("Guilty Eyes Fever", "TVアニメ1期Blu-ray アニメイト全巻購入特典", "Guilty Kiss", "畑 亜貴", "本多友紀(Arte Refact)", "酒井拓也(Arte Refact)", "2017-03-24", 2, 1),
("P.S.の向こう側", "TVアニメ1期Blu-ray ゲーマーズ全巻購入特典", "CYaRon！", "畑 亜貴", "岡本健介", "渡辺和紀", "2017-03-24", 2, 1),
("LONELY TUNING", "TVアニメ1期Blu-ray ソフマップ全巻購入特典", "AZALEA", "畑 亜貴", "Kon-K", "Kon-K", "2017-03-24", 2, 1),
("HAPPY PARTY TRAIN", "HAPPY PARTY TRAIN", "Aqours", "畑 亜貴", "渡辺拓也", "EFFY", "2017-04-05", 2, 1),
("SKY JOURNEY", "HAPPY PARTY TRAIN", "Aqours", "畑 亜貴", "早川博隆", "早川博隆", "2017-04-05", 2, 2),
("少女以上の恋がしたい", "HAPPY PARTY TRAIN", "Aqours", "畑 亜貴", "TAKAROT, KOUDAI IWATSUBO", "TAKAROT, Shinji Tanaka", "2017-04-05", 2, 3),
("近未来ハッピーエンド", "近未来ハッピーエンド", "CYaRon！", "畑 亜貴", "藤井亮太", "藤井亮太", "2017-05-10", 2, 1),
("海岸通りで待ってるよ", "近未来ハッピーエンド", "CYaRon！", "畑 亜貴", "渡辺未来", "渡辺未来", "2017-05-10", 2, 2),
("GALAXY HidE and SeeK", "GALAXY HidE and SeeK", "AZALEA", "畑 亜貴", "竹市佳伸", "竹市佳伸", "2017-05-31", 2, 1),
("INNOCENT BIRD", "GALAXY HidE and SeeK", "AZALEA", "畑 亜貴", "江並哲志", "倉内達矢", "2017-05-31", 2, 2),
("コワレヤスキ", "コワレヤスキ", "Guilty Kiss", "畑 亜貴", "佐伯高志", "佐伯高志", "2017-06-21", 2, 1),
("Shadow gate to love", "コワレヤスキ", "Guilty Kiss", "畑 亜貴", "渡辺和紀", "渡辺和紀", "2017-06-21", 2, 2),
("Landing action Yeah!!", "Aqours CLUB CD SET", "Aqours", "畑 亜貴", "光増ハジメ", "TAKAROT", "2017-06-30", 2, 1),
("夏への扉 Never end ver.", "デュオトリオコレクションCD VOL.1 SUMMER VACATION", "桜内梨子, 国木田花丸, 小原鞠莉", "畑 亜貴", "金崎真士", "金崎真士", "2017-08-02", 2, 1),
("真夏は誰のモノ？", "デュオトリオコレクションCD VOL.1 SUMMER VACATION", "黒澤ダイヤ, 黒澤ルビィ", "畑 亜貴", "原田 篤(Arte Refact)", "原田 篤(Arte Refact)", "2017-08-02", 2, 2),
("地元愛♡満タン☆サマーライフ", "デュオトリオコレクションCD VOL.1 SUMMER VACATION", "渡辺曜, 津島善子", "畑 亜貴", "石倉誉之", "石倉誉之", "2017-08-02", 2, 3),
("夏の終わりの雨音が", "デュオトリオコレクションCD VOL.1 SUMMER VACATION", "高海千歌, 松浦果南", "畑 亜貴", "片桐周太郎", "江上浩太郎", "2017-08-02", 2, 4),
("未来の僕らは知ってるよ", "未来の僕らは知ってるよ", "Aqours", "畑 亜貴", "光増ハジメ", "EFFY", "2017-10-25", 2, 1),
("君の瞳を巡る冒険", "未来の僕らは知ってるよ", "Aqours", "畑 亜貴", "渡辺和紀", "渡辺和紀", "2017-10-25", 2, 2),
("勇気はどこに？君の胸に！", "勇気はどこに？君の胸に！", "Aqours", "畑 亜貴", "小高光太郎, UiNA", "小高光太郎", "2017-11-15", 2, 1),
("“MY LIST” to you!", "勇気はどこに？君の胸に！", "Aqours", "畑 亜貴", "原 知也", "ラムシーニ", "2017-11-15", 2, 2),
("MY舞☆TONIGHT", "MY舞☆TONIGHT／MIRACLE WAVE", "Aqours", "畑 亜貴", "EFFY", "EFFY", "2017-11-29", 2, 1),
("MIRACLE WAVE", "MY舞☆TONIGHT／MIRACLE WAVE", "Aqours", "畑 亜貴", "酒井拓也(Arte Refact)", "脇 眞富(Arte Refact)", "2017-11-29", 2, 2),
("Awaken the power", "Awaken the power", "Saint Aqours Snow", "畑 亜貴", "河田貴央", "河田貴央", "2017-12-20", 2, 1),
("CRASH MIND", "Awaken the power", "Saint Snow", "畑 亜貴", "宮崎 誠", "宮崎 誠", "2017-12-20", 2, 2),
("DROPOUT!?", "Awaken the power", "Saint Snow", "畑 亜貴", "馬渕直純", "馬渕直純", "2017-12-20", 2, 3),
("One More Sunshine Story", "TVアニメ2期Blu-ray第1巻特装限定版", "高海千歌", "畑 亜貴", "EFFY", "EFFY", "2017-12-22", 2, 1),
("WATER BLUE NEW WORLD", "WATER BLUE NEW WORLD／WONDERFUL STORIES", "Aqours", "畑 亜貴", "佐伯高志", "佐伯高志", "2018-01-17", 2, 1), -- ストリングスアレンジ：倉内達矢
("WONDERFUL STORIES", "WATER BLUE NEW WORLD／WONDERFUL STORIES", "Aqours", "畑 亜貴", "Carlos K.", "EFFY", "2018-01-17", 2, 2),
("おやすみなさん！", "TVアニメ2期Blu-ray第2巻特装限定版", "国木田花丸", "畑 亜貴", "白須賀 悟, 増田基生", "白須賀 悟, 増田基生", "2018-01-26", 2, 1),
("in this unstable world", "TVアニメ2期Blu-ray第3巻特装限定版", "津島善子", "畑 亜貴", "神谷 礼", "神谷 礼", "2018-02-23", 2, 1),
("Pianoforte Monologue", "TVアニメ2期Blu-ray第3巻特装限定版", "桜内梨子", "畑 亜貴", "青木宏憲, 廣澤優也", "青木宏憲, 廣澤優也", "2018-02-23", 2, 2),
("Beginner's Sailing", "TVアニメ2期Blu-ray第4巻特装限定版", "渡辺曜", "畑 亜貴", "酒井拓也(Arte Refact)", "酒井拓也(Arte Refact)", "2018-03-23", 2, 1),
("RED GEM WINK", "TVアニメ2期Blu-ray第5巻特装限定版", "黒澤ルビィ", "畑 亜貴", "高田 暁", "高田 暁", "2018-04-24", 2, 1),
("WHITE FIRST LOVE", "TVアニメ2期Blu-ray第5巻特装限定版", "黒澤ダイヤ", "畑 亜貴", "渡辺拓也", "渡辺拓也", "2018-04-24", 2, 2),
("New winding road", "TVアニメ2期Blu-ray第6巻特装限定版", "小原鞠莉", "畑 亜貴", "宮崎 誠", "宮崎 誠", "2018-05-25", 2, 1),
("さかなかなんだか？", "TVアニメ2期Blu-ray第6巻特装限定版", "松浦果南", "畑 亜貴", "設楽哲也", "設楽哲也", "2018-05-25", 2, 2),
("キセキヒカル", "TVアニメ2期Blu-ray第7巻特装限定版", "Aqours", "畑 亜貴", "加藤達也", "加藤達也", "2018-06-22", 2, 1),
("Guilty!? Farewell party", "TVアニメ2期Blu-ray アニメイト全巻購入特典", "Guilty Kiss", "畑 亜貴", "YASUSHI WATANABE", "YASUSHI WATANABE", "2018-06-22", 2, 1),
("サクラバイバイ", "TVアニメ2期Blu-ray ゲーマーズ全巻購入特典", "CYaRon！", "畑 亜貴", "高田 暁", "高田 暁", "2018-06-22", 2, 1),
("卒業ですね", "TVアニメ2期Blu-ray ソフマップ全巻購入特典", "AZALEA", "畑 亜貴", "早川博隆", "TECHNOBOYS PULCRAFT GREEN-FUND", "2018-06-22", 2, 1),
("ホップ・ステップ・ワーイ！", "Aqours CLUB CD SET 2018", "Aqours", "畑 亜貴", "光増ハジメ", "光増ハジメ", "2018-06-30", 2, 1),
("Thank you, FRIENDS!!", "Thank you, FRIENDS!!", "Aqours", "畑 亜貴", "TAKAROT, イワツボコーダイ", "TAKAROT", "2018-08-01", 2, 1),
("No.10", "Thank you, FRIENDS!!", "Aqours", "畑 亜貴", "Akira Sunset", "APAZZI", "2018-08-01", 2, 2),
("ハジマリロード", "劇場版学年別CD付前売券(1年生)", "津島善子, 国木田花丸, 黒澤ルビィ", "畑 亜貴", "TAKAROT, FUNK UCHINO, Ankle Break", "TAKAROT", "2018-11-24", 2, 1),
("Marine Border Parasol", "劇場版学年別CD付前売券(2年生)", "高海千歌, 桜内梨子, 渡辺曜", "畑 亜貴", "Akira Sunset, ulala", "高田 暁", "2018-11-24", 2, 1),
("予測不可能Driving!", "劇場版学年別CD付前売券(3年生)", "松浦果南, 黒澤ダイヤ, 小原鞠莉", "畑 亜貴", "pw.a, Tomomi Ogata", "pw.a", "2018-11-24", 2, 1),
("僕らの走ってきた道は・・・", "僕らの走ってきた道は・・・／Next SPARKLING!!", "Aqours", "畑 亜貴", "EFFY", "EFFY", "2019-01-23", 2, 1),
("Next SPARKLING!!", "僕らの走ってきた道は・・・／Next SPARKLING!!", "Aqours", "畑 亜貴", "Carlos K.", "Carlos K.", "2019-01-23", 2, 2),
("逃走迷走メビウスループ", "逃走迷走メビウスループ／Hop? Stop? Nonstop!", "松浦果南, 黒澤ダイヤ, 小原鞠莉", "畑 亜貴", "山口朗彦", "山口朗彦", "2019-01-30", 2, 1),
("Hop? Stop? Nonstop!", "逃走迷走メビウスループ／Hop? Stop? Nonstop!", "Aqours", "畑 亜貴", "Kanata Okajima, Keisuke Koyama", "Keisuke Koyama", "2019-01-30", 2, 2),
("Believe again", "Believe again／Brightest Melody／Over The Next Rainbow", "Saint Snow", "畑 亜貴", "河田貴央", "河田貴央", "2019-02-06", 2, 1),
("Brightest Melody", "Believe again／Brightest Melody／Over The Next Rainbow", "Aqours", "畑 亜貴", "光増ハジメ", "EFFY", "2019-02-06", 2, 2),
("Over The Next Rainbow", "Believe again／Brightest Melody／Over The Next Rainbow", "Saint Aqours Snow", "畑 亜貴", "Kanata Okajima, TAKAROT", "TAKAROT, Shinji Tanaka", "2019-02-06", 2, 3),
("Jump up HIGH!!", "Aqours CLUB CD SET 2019", "Aqours", "畑 亜貴", "Kanata Okajima, KOUDAI IWATSUBO, TAKAROT", "TAKAROT", "2019-06-30", 2, 1),
("i-n-g, I TRY!!", "劇場版Blu-ray特装限定版", "Aqours", "畑 亜貴", "増田武史", "増田武史", "2019-07-26", 2, 1),
("冒険Type A, B, C!!", "リアル脱出ゲーム『学校祭ライブ中止の危機からの脱出』特典CD", "Aqours", "畑 亜貴", "倉内達矢", "倉内達矢", "2019-07-26", 2, 1),
("未体験HORIZON", "未体験HORIZON", "Aqours", "畑 亜貴", "小高光太郎, UiNA", "小高光太郎", "2019-09-25", 2, 1),
("Deep Resonance", "未体験HORIZON", "Aqours", "畑 亜貴", "桑原 聖(Arte Refact)", "酒井拓也(Arte Refact)", "2019-09-25", 2, 2),
("Dance with Minotaurus", "未体験HORIZON", "Aqours", "畑 亜貴", "増田武史", "増田武史", "2019-09-25", 2, 3),
("KOKORO Magic “A to Z”", "KOKORO Magic “A to Z”", "Aqours", "畑 亜貴", "EFFY", "EFFY", "2019-10-30", 2, 1),
("Wake up, Challenger!!", "KOKORO Magic “A to Z”", "Aqours", "畑 亜貴", "河田貴央", "河田貴央", "2019-10-30", 2, 2),
("New Romantic Sailors", "New Romantic Sailors", "Guilty Kiss", "畑 亜貴", "杉山勝彦, ulala", "ulala", "2019-11-27", 2, 1),
("Love Pulsar", "New Romantic Sailors", "Guilty Kiss", "畑 亜貴", "渡辺未来", "渡辺未来", "2019-11-27", 2, 2),
("Phantom Rocket Adventure", "New Romantic Sailors", "Guilty Kiss", "畑 亜貴", "本多友紀(Arte Refact)", "本多友紀(Arte Refact)", "2019-11-27", 2, 3),
("Braveheart Coaster", "Braveheart Coaster", "CYaRon！", "畑 亜貴", "高田 暁", "高田 暁", "2019-12-04", 2, 1),
("CHANGELESS", "Braveheart Coaster", "CYaRon！", "畑 亜貴", "前口 渉", "前口 渉", "2019-12-04", 2, 2),
("コドク・テレポート", "Braveheart Coaster", "CYaRon！", "畑 亜貴", "原田 篤(Arte Refact)", "矢鴇つかさ(Arte Refact)", "2019-12-04", 2, 3),
("Amazing Travel DNA", "Amazing Travel DNA", "AZALEA", "畑 亜貴", "山田竜平", "山田竜平", "2019-12-11", 2, 1),
("空中恋愛論", "Amazing Travel DNA", "AZALEA", "畑 亜貴", "Kohei by SIMONSAYZ", "Kohei by SIMONSAYZ", "2019-12-11", 2, 2),
("メイズセカイ", "Amazing Travel DNA", "AZALEA", "畑 亜貴", "黒川陽介", "黒川陽介", "2019-12-11", 2, 3),
