('TOKIMEKI Runners', 'TOKIMEKI Runners', "虹ヶ咲学園スクールアイドル同好会", '畑 亜貴', '矢鴇つかさ(Arte Refact)', '矢鴇つかさ(Arte Refact)', '2018-11-21', 3, 1),
('夢への一歩', 'TOKIMEKI Runners', "上原歩夢", 'Akira Sunset', 'Akira Sunset', '菊池博人', '2018-11-21', 3, 2),
('ダイアモンド', 'TOKIMEKI Runners', "中須かすみ", '鈴木エレカ, JOE', '鈴木エレカ, JOE', 'tasuku', '2018-11-21', 3, 3),
('あなたの理想のヒロイン', 'TOKIMEKI Runners', "桜坂しずく", '月見草', '月見草', '遠藤ナオキ', '2018-11-21', 3, 4),
('Starlight', 'TOKIMEKI Runners', "朝香果林", 'BEATNINE', 'BEATNINE', 'BEATNINE', '2018-11-21', 3, 5),
('めっちゃGoing!!', 'TOKIMEKI Runners', "宮下愛", 'Akira Sunset', 'Akira Sunset, Carlos K.', 'Carlos K.', '2018-11-21', 3, 6),
('眠れる森に行きたいな', 'TOKIMEKI Runners', "近江彼方", 'Ryota Saito, Diz', 'Ryota Saito, Diz', 'Ryota Saito, Diz', '2018-11-21', 3, 7),
('CHASE!', 'TOKIMEKI Runners', "優木せつ菜", '鈴木エレカ, JOE', '鈴木エレカ, JOE', 'tasuku', '2018-11-21', 3, 8),
('Evergreen', 'TOKIMEKI Runners', "エマ・ヴェルデ", 'Ryota Saito, 近谷直之', 'Ryota Saito, 近谷直之', 'Ryota Saito, 近谷直之', '2018-11-21', 3, 9),
('ドキピポ☆エモーション', 'TOKIMEKI Runners', "天王寺璃奈", 'NOVECHIKA, 菊池博人', 'NOVECHIKA, 菊池博人', 'NOVECHIKA, 菊池博人', '2018-11-21', 3, 10),
('開花宣言', 'Love U my friends', "上原歩夢", 'Akira Sunset', 'Akira Sunset', '遠藤ナオキ', '2019-10-02', 3, 1),
('☆ワンダーランド☆', 'Love U my friends', "中須かすみ", '鈴木エレカ', 'NOVECHIKA, TETTA', 'NOVECHIKA, TETTA', '2019-10-02', 3, 2),
('オードリー', 'Love U my friends', "桜坂しずく", '月見草', '月見草', '菊池博人', '2019-10-02', 3, 3),
('Wish', 'Love U my friends', "朝香果林", 'BEATNINE', 'Carlos K.', 'Carlos K., JOE', '2019-10-02', 3, 4),
('友 & 愛', 'Love U my friends', "宮下愛", 'Akira Sunset', 'Carlos K.', 'Carlos K., Konnie Aoki', '2019-10-02', 3, 5),
('My Own Fairy-Tale', 'Love U my friends', "近江彼方", 'Ryota Saito', 'Ryota Saito, Diz', 'Ryota Saito, Diz', '2019-10-02', 3, 6),
('MELODY', 'Love U my friends', "優木せつ菜", '鈴木エレカ', '鈴木まなか, Hiroki Sagawa', 'サイトウ リョースケ', '2019-10-02', 3, 7),
('声繋ごうよ', 'Love U my friends', "エマ・ヴェルデ", 'Ryota Saito', '浦島健太, 山本 匠', '浦島健太, 山本 匠', '2019-10-02', 3, 8),
('テレテレパシー', 'Love U my friends', "天王寺璃奈", 'NOVECHIKA, クボナオキ', 'クボナオキ', '縄田寿志', '2019-10-02', 3, 9),
('Love U my friends', 'Love U my friends', "虹ヶ咲学園スクールアイドル同好会", 'Kanata Okajima', 'Keisuke Koyama, Shunsuke Harada', 'Keisuke Koyama', '2019-10-02', 3, 10),
('SUPER NOVA', 'SUPER NOVA', "DiverDiva", 'Dummy Dog', 'Dummy Dog', 'Dummy Dog', '2020-02-12', 3, 1),
('Love Triangle', 'SUPER NOVA', "DiverDiva", "Ayaka Miyake, 栗原 暁（Jazzin’park）", "久保田真悟（Jazzin’park）, 栗原 暁（Jazzin’park）", "久保田真悟（Jazzin’park）", '2020-02-12', 3, 2),
('Dream Land！Dream World！', 'Dream Land！Dream World！', "A・ZU・NA", 'hot tears', '景山将太', 'MEGAneCOMIC', '2020-02-12', 3, 1),
('Cheer for you!!', 'Dream Land！Dream World！', "A・ZU・NA", 'Ayaka Miyake', 'hot tears, Sheeta.C', 'hot tears, Sheeta.C', '2020-02-12', 3, 2),
('Sing & Smile!!', 'Sing & Smile!!', "QU4RTZ", 'Carlos K.', '丸谷マナブ, Carlos K.', 'Carlos K.', '2020-02-12', 3, 1),
('Beautiful Moonlight', 'Sing & Smile!!', "QU4RTZ", 'Ayaka Miyake', 'ygarshy', 'PASSiON KiNG', '2020-02-12', 3, 2),
